/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingsystem;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

public class loginpage extends javax.swing.JFrame {

    /**
     * Creates new form loginpage
     */
    public loginpage() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtusername = new javax.swing.JTextField();
        jbtnexit = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnlogin = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.pink);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel2.setText("User Login");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 0, 230, 60);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 120, 190, 60);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 220, 160, 50);

        jtxtusername.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jPanel1.add(jtxtusername);
        jtxtusername.setBounds(340, 130, 250, 40);

        jbtnexit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.setPreferredSize(new java.awt.Dimension(73, 29));
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnexit);
        jbtnexit.setBounds(500, 350, 120, 29);

        jbtnreset.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnreset);
        jbtnreset.setBounds(360, 350, 120, 30);

        jbtnlogin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jbtnlogin.setText("Login");
        jbtnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnloginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnlogin);
        jbtnlogin.setBounds(200, 350, 140, 30);

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(jPassword);
        jPassword.setBounds(340, 220, 250, 40);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel6.setText("Voter can only be logged in on the given time slot.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(910, 70, 430, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel5.setText("Login with the given credentials");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(870, 30, 330, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel7.setText("Voter will have 10sec to cast their Vote.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(970, 120, 410, 40);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel8.setText("Once Voter logged in they can find different parties to vote.");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1030, 180, 510, 40);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel9.setText("Click on Vote for your desired party to cast your Vote.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(970, 240, 470, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 51));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel10.setText("Once Voter clicks on Vote their responce will be saved and cannot be");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(920, 280, 670, 50);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel11.setText("A dialogue box appears that you have successfully Voted, this is confirmation");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(870, 330, 690, 40);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel12.setText(" that your vote has been casted successfully ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(870, 360, 420, 40);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel14.setText(" changed. ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(920, 290, 130, 70);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingsystem/icons/a2.JPG"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(431, 430, 290, 350);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingsystem/icons/modi3.JPG"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 430, 425, 350);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingsystem/icons/r2.JPG"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(690, 430, 460, 430);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingsystem/icons/yogi.JPG"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1120, 430, 460, 360);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel13.setText("Voter will automatically logged out of system once the vote is casted.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(800, 390, 630, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingsystem/icons/back2.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 800));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, -150, 1920, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1636, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        jtxtusername.setText(null);
        jPassword.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnloginActionPerformed
        new Votepage2().setVisible(true);
    }//GEN-LAST:event_jbtnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnlogin;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JTextField jtxtusername;
    // End of variables declaration//GEN-END:variables

    private void systeExit()
    {
        WindowEvent winCloseing = new  WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}

